/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.udesc.superfatorial;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author udesc
 */
public class Janela extends javax.swing.JFrame {

    SuperFatorial sFat;
    SuperFatorialCached sCFat;
    SuperFatorialDiskCached sDCFat;
    /**
     * Creates new form Janela
     */
    public Janela() {
        this.sFat = new SuperFatorial();
        this.sCFat = new SuperFatorialCached();
        this.sDCFat = new SuperFatorialDiskCached();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcularSuperFatorialCached1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        valorEntrada = new javax.swing.JTextField();
        calcularSuperFatorialCached = new javax.swing.JButton();
        calcularSuperFatorial = new javax.swing.JButton();
        mostrarSupCached = new javax.swing.JButton();
        calcularSuperFatorialDiskCached = new javax.swing.JButton();

        calcularSuperFatorialCached1.setText("CALCULAR COM CACHED");
        calcularSuperFatorialCached1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSuperFatorialCached1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SuperFatorial");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Digite o número:");

        valorEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorEntradaActionPerformed(evt);
            }
        });

        calcularSuperFatorialCached.setText("CALCULAR COM CACHED");
        calcularSuperFatorialCached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSuperFatorialCachedActionPerformed(evt);
            }
        });

        calcularSuperFatorial.setText("CALCULAR SEM CACHED");
        calcularSuperFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSuperFatorialActionPerformed(evt);
            }
        });

        mostrarSupCached.setText("TABELA COM VALORES");
        mostrarSupCached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarSupCachedActionPerformed(evt);
            }
        });

        calcularSuperFatorialDiskCached.setText("CALCULAR COM DISCO");
        calcularSuperFatorialDiskCached.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularSuperFatorialDiskCachedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(mostrarSupCached))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(calcularSuperFatorial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularSuperFatorialCached)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcularSuperFatorialDiskCached))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorEntrada)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularSuperFatorialCached)
                    .addComponent(calcularSuperFatorial)
                    .addComponent(calcularSuperFatorialDiskCached))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrarSupCached)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valorEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorEntradaActionPerformed

    private void calcularSuperFatorialCachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSuperFatorialCachedActionPerformed
        try {
            JOptionPane.showMessageDialog(this, sCFat.getSuperFatorial(Integer.valueOf(valorEntrada.getText())));
        } catch (InputException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } catch (NumberFormatException ex){
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, "valor não inteiro digitado");
            JOptionPane.showMessageDialog(this, "Valor digitado não é um inteiro, tente novamente");
        }
    }//GEN-LAST:event_calcularSuperFatorialCachedActionPerformed

    private void calcularSuperFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSuperFatorialActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(this, sFat.getSuperFatorial(Integer.valueOf(valorEntrada.getText())));
        } catch (InputException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } catch (NumberFormatException ex){
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, "valor não inteiro digitado");
            JOptionPane.showMessageDialog(this, "Valor digitado não é um inteiro, tente novamente");
        }
    }//GEN-LAST:event_calcularSuperFatorialActionPerformed

    private void mostrarSupCachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarSupCachedActionPerformed
        // TODO add your handling code here:
        SuperFatorialCachedTable cachedTable=new SuperFatorialCachedTable(this,sCFat.getCacheFat(),sCFat.getCacheSupFat());
        this.setVisible(false);
        cachedTable.setVisible(true);
    }//GEN-LAST:event_mostrarSupCachedActionPerformed

    private void calcularSuperFatorialCached1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSuperFatorialCached1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcularSuperFatorialCached1ActionPerformed

    private void calcularSuperFatorialDiskCachedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularSuperFatorialDiskCachedActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(this, sDCFat.getSuperFatorial(Integer.valueOf(valorEntrada.getText())));
        } catch (InputException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
        } catch (NumberFormatException ex){
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, "valor não inteiro digitado");
            JOptionPane.showMessageDialog(this, "Valor digitado não é um inteiro, tente novamente");
        }
    }//GEN-LAST:event_calcularSuperFatorialDiskCachedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularSuperFatorial;
    private javax.swing.JButton calcularSuperFatorialCached;
    private javax.swing.JButton calcularSuperFatorialCached1;
    private javax.swing.JButton calcularSuperFatorialDiskCached;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mostrarSupCached;
    private javax.swing.JTextField valorEntrada;
    // End of variables declaration//GEN-END:variables
}
