/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.udesc.superfatorial;

import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author smlle
 */
public class SuperFatorialCachedTable extends javax.swing.JFrame {

    private final HashMap<Integer, BigInteger> cacheFat;
    private final HashMap<Integer, BigInteger> cacheSupFat;
    private final Janela father;

    /**
     * Creates new form SuperFatorialCachedTable
     */
    public SuperFatorialCachedTable(Janela father, HashMap<Integer, BigInteger> cacheFat, HashMap<Integer, BigInteger> cacheSupFat) {
        this.father = father;
        this.cacheFat = cacheFat;
        this.cacheSupFat = cacheSupFat;
        initComponents();
        tableFat.setModel(toTableModel());
        tableSupFat.setModel(toTableSupModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFat = new javax.swing.JTable();
        voltarBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSupFat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableFat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableFat);

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        tableSupFat.setModel(tableSupFat.getModel());
        jScrollPane2.setViewportView(tableSupFat);

        jLabel1.setText("Tabela Fatorial");

        jLabel2.setText("Tabela SuperFatorial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(voltarBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        // TODO add your handling code here:
        father.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    private void populateTable() {
        Object[][] tableFatData = new Object[cacheFat.keySet().size()][15];
        Object[][] tableSupFatData = new Object[cacheSupFat.keySet().size()][15];
        int index = 0;
        for (Map.Entry<?, ?> entry : cacheFat.entrySet()) {
            tableFatData[index][0] = entry.getKey();
            tableFatData[index][1] = entry.getValue();
            index++;
        }
    }

    public  TableModel toTableModel() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Fatorial", "Valor"}, 0
        );
        cacheFat.entrySet().forEach((entry) -> {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        });
        return model;
    }
    
    public  TableModel toTableSupModel() {
        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Super Fatorial", "Valor"}, 0
        );
        cacheSupFat.entrySet().forEach((entry) -> {
            model.addRow(new Object[]{entry.getKey(), entry.getValue()});
        });
        return model;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableFat;
    private javax.swing.JTable tableSupFat;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
